#!/bin/bash

curl -sS https://starship.rs/install.sh | sh

wget -P ~/.fonts https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip && cd ~/.fonts && unzip JetBrainsMono.zip && rm JetBrainsMono.zip && fc-cache -fv

wget https://raw.githubusercontent.com/Kecubunk/mybash/main/config.txt

cat config.txt >> ~/.bashrc

wget -P ~/.config/ https://raw.githubusercontent.com/Kecubunk/mybash/main/starship.toml

rm -f config.txt


